# Generated by Django 3.1.1 on 2020-10-06 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stud_mgmt_sys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='students',
            name='student_image',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='super_image',
        ),
    ]
