# Generated by Django 3.1.1 on 2020-10-06 17:40

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_mgmt_sys', '0003_auto_20201006_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='contact phone number', max_length=31),
        ),
    ]
