# Generated by Django 3.1.1 on 2020-10-11 13:17

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_mgmt_sys', '0004_auto_20201006_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='gender',
            field=models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='students',
            name='student_photo',
            field=models.ImageField(null=True, upload_to='students_photo'),
        ),
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
