# Generated by Django 3.1.1 on 2020-10-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_mgmt_sys', '0007_auto_20201011_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supervisor',
            name='supervisor_photo',
            field=models.ImageField(null=True, upload_to='supervisors_photo'),
        ),
    ]
