# Generated by Django 3.1.1 on 2020-10-16 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_mgmt_sys', '0011_auto_20201014_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_table',
            name='day',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance_report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance_report',
            name='status',
            field=models.CharField(choices=[('absent', 'absent'), ('present', 'present')], max_length=100),
        ),
        migrations.AlterField(
            model_name='attendance_report',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='attendance_table',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='attendance_table',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='attendance_table',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
